Add README.md
OAK-Foundation/substrate-simple-template pull request #1
Opened 2021-06-10 09:57 UTC by imstar15

2021-06-10 18:25 UTC, chrisli30 requested changes

2021-06-10 18:25 UTC, chrisli30 commented on README.md
> +A simple template to bootstrap a Substrate node with BABE consensus
BABE(Nominated Proof of Stake) consensus

and link to the text https://substrate.dev/docs/en/knowledgebase/advanced/consensus#babe

2021-06-10 18:25 UTC, chrisli30 commented on README.md
> +Follow the steps below to get started with the Node Template.
the node template

2021-06-10 18:25 UTC, chrisli30 commented on README.md
> +subcommands:
subcommands 是什么意思？

2021-06-10 18:25 UTC, chrisli30 commented on README.md
> +you terminate the process. After the project has been built, there are other ways to launch the
这句的意思是会新启动一个命令行窗口？

2021-06-10 18:25 UTC, chrisli30 commented on README.md
> +Generate pubic key from a secret phrase.
要加上注释，这个私钥是开发专用，不能用在任何其他地方

忠伟写的node-template的里面的readme也有这句

2021-06-10 18:25 UTC, chrisli30 commented on README.md
> +# Put your mnemonic here.
Copy paste your mnemonic here.

2021-06-10 18:25 UTC, chrisli30 commented on README.md
> +```
这个代码块是什么意思？

2021-06-10 18:25 UTC, chrisli30 commented on README.md
> +Idle (2 peers), best: #5 (0x1d5a…f4f2), finalized #3 (0xe2b9…3056), ⬇ 2.3kiB/s ⬆ 2.4kiB/s
这里多复制两行输出

2021-06-10 18:25 UTC, chrisli30 commented on README.md
> +Re-launch nodes and the network can finalize blocks.
Since we have changed the configuration, we need to re-launch **all three?** nodes by **cargo command?**

relaunch几个nodes？
怎么启动？

2021-06-11 01:13 UTC, imstar15 commented on README.md
> +subcommands:
subcommand这句话，我是照抄node-template的，子命令的意思

2021-06-11 01:18 UTC, imstar15 commented on README.md
> +```
这个意思是把上面生成的文本，替换到...的位置，他看到那段代码，他自然就会懂

2021-06-11 01:48 UTC, imstar15 commented on README.md
> +Idle (2 peers), best: #5 (0x1d5a…f4f2), finalized #3 (0xe2b9…3056), ⬇ 2.3kiB/s ⬆ 2.4kiB/s
Fixed

2021-06-11 01:49 UTC, imstar15 commented on README.md
> +Re-launch nodes and the network can finalize blocks.
就是上面提到的3个nodes，先把它们结束了，再重新运行对应的命令就可以了

2021-06-11 01:49 UTC, imstar15 commented on README.md
> +# Put your mnemonic here.
Fixed

2021-06-11 01:50 UTC, imstar15 commented on README.md
> +you terminate the process. After the project has been built, there are other ways to launch the
不启动新窗口

2021-06-11 02:11 UTC, imstar15 commented on README.md
> +Generate pubic key from a secret phrase.
Fixed

2021-06-11 03:02 UTC, chrisli30 requested changes

2021-06-11 03:02 UTC, chrisli30 commented on README.md
> +Generate pubic key from a secret phrase. This secret phrase is dedicated to development and cannot be used in any other place.
should not be used in any other places.

2021-06-11 03:02 UTC, chrisli30 commented on README.md
> +Generate pubic key from a secret phrase. This secret phrase is dedicated to development and cannot be used in any other place.
same as above

2021-06-11 03:02 UTC, chrisli30 commented on README.md
> +Re-launch nodes and the network can finalize blocks.
那你把你的这个评论写在文档里，注明 all 3 nodes，重新运行哪一个章节的，或者哪几个命令？

2021-06-11 03:02 UTC, chrisli30 commented on README.md
> +2021-06-11 09:40:58  💤 Idle (2 peers), best: #7 (0x1f7b…431b), finalized #5 (0x4064…6d67), ⬇ 2.7kiB/s ⬆ 2.6kiB/s
显示10 行就够了。

2021-06-11 03:12 UTC, imstar15 commented on README.md
> +2021-06-11 09:40:58  💤 Idle (2 peers), best: #7 (0x1f7b…431b), finalized #5 (0x4064…6d67), ⬇ 2.7kiB/s ⬆ 2.6kiB/s
Fixed

2021-06-11 03:12 UTC, imstar15 commented on README.md
> +Generate pubic key from a secret phrase. This secret phrase is dedicated to development and cannot be used in any other place.
Fixed

2021-06-11 03:12 UTC, imstar15 commented on README.md
> +Generate pubic key from a secret phrase. This secret phrase is dedicated to development and cannot be used in any other place.
Fixed

2021-06-11 03:20 UTC, imstar15 commented on README.md
> +2021-06-11 09:40:58  💤 Idle (2 peers), best: #7 (0x1f7b…431b), finalized #5 (0x4064…6d67), ⬇ 2.7kiB/s ⬆ 2.6kiB/s
Fixed

2021-06-11 03:23 UTC, chrisli30 requested changes

2021-06-11 03:23 UTC, chrisli30 commented on README.md
> +```
Replace the session keys from `vec![...]` in `node/cli/src/chain_spec.rs` with above generated keys.

2021-06-11 03:23 UTC, chrisli30 commented on README.md
> +Re-launch nodes and the network can finalize blocks.
这个comment还没处理

2021-06-11 03:47 UTC, chrisli30 approved these changes

2021-06-11 03:53 UTC, merged